- id: doi:10.1097/HP.0000000000001784
  image: 
  date: '2024-03-1'
  title: 'Response to Galiano'
  publisher: 'Health Physics'

- id: doi:10.1016/j.psep.2024.01.007
  image: 
  date: '2024-3-1'
  title: 'Performance analysis of various machine learning algorithms for CO2 leak prediction and characterization in geo-sequestration injection wells'
  publisher: 'Process Safety and Environmental Protection'

- id: doi:10.1097/HP.0000000000001732
  image: 
  date: '2023-10-1'
  title: 'Response to McCollough et al.'
  publisher: 'Health Physics'

- id: doi:10.2118/216749-MS
  image: 
  date: '2023-10-2'
  title: 'Visual Twin for Pipeline Leak Detection'
  publisher: 'Abu Dhabi International Petroleum Exhibition and Conference (ADIPEC)'

- id: doi:10.1109/MCOM.004.2200627
  image: 
  date: '2023-09-1'
  title: 'Immersive Media and the Metaverse'
  publisher: 'IEEE Communications Magazine ( Volume: 61, Issue: 9, September 2023)'

- id: doi:10.1097/HP.0000000000001705
  image: 
  date: '2023-09-1'
  title: 'Radiation exposure from the patient perspective: an argument for the inclusion of dose history'
  publisher: 'Health Physics'

- id: url:https://ieeexplore.ieee.org/abstract/document/10019614
  image: https://www.vaclab.ca/images/foldpaper.PNG
  date: '2022-12-5'
  title: 'On Requirements for Field of Light Displays to Pass the Visual Turing Test'
  publisher: '2022 IEEE International Symposium on Multimedia (ISM)'

- id: url:https://www.cs.mun.ca/~mhamilton/papers/Hamilton.pdf
  image: https://www.vaclab.ca/images/foldpaper.PNG
  date: '2021-10-24'
  title: 'Visualization Using Field of Light Displays: Opportunities and New Questions'
  publisher: 'VisXVision: Workshop on Novel Directions in Vision Science and Visualization Research at IEEE Visualization 2021 Conference.'

- id: url:https://www.cs.mun.ca/~mhamilton/papers/nwells-hamilton-Necec2021.pdf
  image: https://www.vaclab.ca/images/wellspaper.png
  date: '2021-11-18'
  title: Towards Immersive Cinematic Video for Immersive Displays
  publisher: The 30th Newfoundland Electrical and Computer Engineering Conference (NECEC), St. John's, Canada.

- id: url:https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-159/MP-MSG-159-08.pdf
  date: 2018-11-1
  title: 'Holographic Displays: Emerging Technologies and Use Cases in Defence Applications'
  image: 
  publisher: 'NATO MSG-159 2018 Annual M&S Conference.'

- id: doi:10.4043/27392-MS
  publisher: OTC Arctic Technology Conference, St. John's, Canada, October 2016.
  image: https://www.vaclab.ca/images/flowvasepaper.PNG

- id: doi:10.4043/25525-MS
  publisher: OTC Arctic Technology Conference, Copenhagen, Denmark, March 2015.
  image: https://www.vaclab.ca/images/vasepaper.PNG

- id: doi:10.1002/sdtp.12268
  image: https://www.vaclab.ca/images/simpaper.PNG

- id: doi:10.1529/biophysj.107.116053
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006349508703783-gr2.jpg

- id: doi:10.1007/11847250_21

- id: doi:10.4230/DagSemProc.07281.3

- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:AvfA0Oy_GE0C
  date: '2025-01-01'
  title: 'Comprehensive analysis of leak impacts on liquid-gas multiphase flow using statistical, wavelet transform, and machine learning approaches'
  authors: 'H Ferroudji, MS Khan, A Barooah, WA Al-Ammari, I Hassan, R Hassan, ...'
  publisher: 'Process Safety and Environmental Protection 194, 825-843, 2025'

- id: url:Link
  date: 'Year-01-01'
  title: 'Title'
  authors: 'Authors'
  publisher: 'Journal'
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:p__nRnzSRKYC
  title: "Newfoundland and Labrador Breast Screening (NLBS) Dataset (NL-Breast-Screen)"
  authors:
  - "E Kendall"
  - "P Hajishafiezahramini"
  - "M Hamilton"
  - "G Doyle"
  - "N Wadden"
  - "..."

  publisher: "Federated Research Data Repository/dépôt fédéré de données de recherche, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:p__nRnzSRKYC"
  image: "https://raw.githubusercontent.com/hamilton101/hamilton101.github.io/main/images/banner.jpg"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&citation_for_view=PWi6hlkAAAAJ:BUYA1_V_uYcC
  title: "Analysis of water-air multiphase flow through a pipeline with two leaks using numerical and experimental methods"
  authors:
  - "H Ferroudji"
  - "M Saad Khan"
  - "A Barooah"
  - "M Azizur Rahman"
  - "I Hassan"
  - "..."

  publisher: "Journal of Dispersion Science and Technology 47 (1), 36-47, 2026"
  date: "2026-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&citation_for_view=PWi6hlkAAAAJ:BUYA1_V_uYcC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:gsN89kCJA0AC
  title: "Development of Machine Learning Models for Multiple Leak Detection in Offshore Gas Pipelines under Single-and Multiphase Flow Conditions"
  authors:
  - "WA Al-Ammari"
  - "AK Sleiti"
  - "Y AbuShanab"
  - "M Hamilton"
  - "A Rashid Hasan"
  - "..."

  publisher: "Journal of Pipeline Systems Engineering and Practice 17 (1), 04025092, 2026"
  date: "2026-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:gsN89kCJA0AC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:tuHXwOkdijsC
  title: "Prompt-Level Contrastive Learning for Context-Aware Multi-modal Image Representation in Medical Diagnosis"
  authors:
  - "G Dai"
  - "Z Tian"
  - "C Xin"
  - "D Dai"
  - "C Wang"
  - "Y Zhang"
  - "H Chen"
  - "M Hamilton"

  publisher: "Pattern Recognition, 113027, 2026"
  date: "2026-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:tuHXwOkdijsC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:MLfJN-KU85MC
  title: "Polarization-Aware CrossGate U-Net for Sea Ice Classification"
  authors:
  - "N Ahmadian"
  - "M Hamilton"
  - "W Huang"

  publisher: "IEEE GEOSCIENCE AND REMOTE SENSING LETTERS 23, 2026"
  date: "2026-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:MLfJN-KU85MC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&citation_for_view=PWi6hlkAAAAJ:AvfA0Oy_GE0C
  title: "Comprehensive analysis of leak impacts on liquid-gas multiphase flow using statistical, wavelet transform, and machine learning approaches"
  authors:
  - "H Ferroudji"
  - "MS Khan"
  - "A Barooah"
  - "WA Al-Ammari"
  - "I Hassan"
  - "R Hassan"
  - "..."

  publisher: "Process Safety and Environmental Protection 194, 825-843, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&citation_for_view=PWi6hlkAAAAJ:AvfA0Oy_GE0C"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:vDijr-p_gm4C
  title: "Full field digital mammography dataset from a population screening program"
  authors:
  - "E Kendall"
  - "P Hajishafiezahramini"
  - "M Hamilton"
  - "G Doyle"
  - "N Wadden"
  - "..."

  publisher: "Scientific Data 12 (1), 1479, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:vDijr-p_gm4C"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:KUbvn5osdkgC
  title: "Multi-Task Learning Network for Medical Image Analysis Guided by Lesion Regions and Spatial Relationships of Tissues"
  authors:
  - "G Dai"
  - "D Dai"
  - "C Wang"
  - "Q Tang"
  - "M Hamilton"
  - "H Chen"
  - "Y Zhang"

  publisher: "IEEE Transactions on Circuits and Systems for Video Technology, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:KUbvn5osdkgC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:vbGhcppDl1QC
  title: "Advancing offshore pipeline safety: Exploring non-invasive Electrical Resistance Tomography for upstream leak response detection Strategy"
  authors:
  - "MS Khan"
  - "H Ferroudji"
  - "A Barooah"
  - "MA Rahman"
  - "I Hassan"
  - "R Hassan"
  - "..."

  publisher: "Flow Measurement and Instrumentation 106, 103013, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:vbGhcppDl1QC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:TIZ-Mc8IlK0C
  title: "Development of Digital/Visual Twin for Real‐Time Leak Detection in Gas Pipelines Under Multiphase Flow Conditions"
  authors:
  - "WA Al‐Ammari"
  - "AK Sleiti"
  - "M Hamilton"
  - "H Ferroudji"
  - "SR Gomari"
  - "I Hassan"
  - "..."

  publisher: "Greenhouse Gases: Science and Technology 15 (5), 513-530, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:TIZ-Mc8IlK0C"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:g3aElNc5_aQC
  title: "AI-Based Adaptive Digital Twin Framework for Real-Time Leak Detection and Localization in Offshore Gas Pipelines"
  authors:
  - "WA Al-Ammari"
  - "AK Sleiti"
  - "M Hamilton"
  - "H Ferroudji"
  - "M Azizur Rahman"
  - "..."

  publisher: "International Conference on Offshore Mechanics and Arctic Engineering 88957 …, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:g3aElNc5_aQC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:ML0RJ9NH7IQC
  title: "Integration of Unsupervised and Supervised Machine Learning Models for Single/Multiple Leak Detection and Localization Using Minimal Sensor Data"
  authors:
  - "W Al-Ammari"
  - "AK Sleiti"
  - "M Hamilton"
  - "H Ferroudji"
  - "SR Gomari"
  - "I Hassan"
  - "..."

  publisher: "21st Global Congress on Process Safety: 2025 Spring Meeting and 21st Global …, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:ML0RJ9NH7IQC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:b1wdh0AR-JQC
  title: "Digital Twin for Pipeline Leak Monitoring"
  authors:
  - "M Hamilton"
  - "H Ferroudji"
  - "M Colbourne"
  - "S Sheppard"
  - "A Barooah"
  - "AK Sleiti"
  - "..."

  publisher: "Abu Dhabi International Petroleum Exhibition and Conference, D031S102R004, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:b1wdh0AR-JQC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:kuK5TVdYjLIC
  title: "Integrating advanced frequency-domain signal processing with machine learning for accurate leak detection in subsurface CO2 storage"
  authors:
  - "S Harati"
  - "SR Gomari"
  - "MA Rahman"
  - "R Hassan"
  - "I Hassan"
  - "AK Sleiti"
  - "..."

  publisher: "Gas Science and Engineering, 205798, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:kuK5TVdYjLIC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:ILKRHgRFtOwC
  title: "Performance Evaluation of Three Deep Learning Models for River ICE Segmentation From Aerial Images"
  authors:
  - "N Ahmadian"
  - "M Hamilton"
  - "W Huang"

  publisher: "2025 IEEE 20th International Symposium on Antenna Technology and Applied …, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:ILKRHgRFtOwC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:L7CI7m0gUJcC
  title: "Adaptive Flight Planning Using Turbulence and Weather Forecasts"
  authors:
  - "SS Nair"
  - "M Hamilton"

  publisher: "2025 IEEE 20th International Symposium on Antenna Technology and Applied …, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:L7CI7m0gUJcC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:tYavs44e6CUC
  title: "A Unified Data Platform for Maritime Analytics and Predictive Modeling in Arctic Operations"
  authors:
  - "B Singh"
  - "J Barnes"
  - "A Kennedy"
  - "M Hamilton"
  - "S Reddy"

  publisher: "POAC`25, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:tYavs44e6CUC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:EYYDruWGBe4C
  title: "Advanced Emissions Profiling of Canadian Icebreaker Vessels: Bridging Calculations, Validating Empirical Data, and Exploring Decarbonization Strategies"
  authors:
  - "SR Chittamuru"
  - "H Matthew"
  - "A Akinturk"
  - "A Kennedy"
  - "J Barnes"
  - "B Singh"

  publisher: "OCEANS 2025 Brest, 1-10, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:EYYDruWGBe4C"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:Z5m8FVwuT1cC
  title: "Advancing Offshore Pipeline Safety: Exploring Non-Invasive Electrical Resistance Tomography for Rapid Upstream Leak Response Detection Strategy"
  authors:
  - "MS Khan"
  - "H Ferroudji"
  - "A Barooah"
  - "I Hassan"
  - "AR Hassan"
  - "AK Sleiti"
  - "..."

  publisher: "Available at SSRN 5142424, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:Z5m8FVwuT1cC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:ILKRHgRFtOwC
  title: "Performance Evaluation of Three Deep Learning Models for River ICE Segmentation From Aerial Images"
  authors:
  - "N Ahmadian"
  - "M Hamilton"
  - "W Huang"

  publisher: "2025 IEEE 20th International Symposium on Antenna Technology and Applied …, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=20&citation_for_view=PWi6hlkAAAAJ:ILKRHgRFtOwC"
- id: url:https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:g3aElNc5_aQC
  title: "AI-Based Adaptive Digital Twin Framework for Real-Time Leak Detection and Localization in Offshore Gas Pipelines"
  authors:
  - "WA Al-Ammari"
  - "AK Sleiti"
  - "M Hamilton"
  - "H Ferroudji"
  - "M Azizur Rahman"
  - "..."

  publisher: "International Conference on Offshore Mechanics and Arctic Engineering 88957 …, 2025"
  date: "2025-01-01"
  link: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=PWi6hlkAAAAJ&cstart=40&citation_for_view=PWi6hlkAAAAJ:g3aElNc5_aQC"
