- id: url:https://www.cs.mun.ca/~mhamilton/papers/Hamilton.pdf
  date: 2021-10-24
  title: 'Visualization Using Field of Light Displays: Opportunities and New Questions'
  publisher: 'VisXVision: Workshop on Novel Directions in Vision Science and Visualization Research at IEEE Visualization 2021 Conference.'
  
- id: url:https://www.cs.mun.ca/~mhamilton/papers/nwells-hamilton-Necec2021.pdf
  date: 2021-11-18
  title: 'Towards Immersive Cinematic Video for Immersive Displays'
  publisher: The 30th Newfoundland Electrical and Computer Engineering Conference (NECEC), St. John's, Canada.
  publisher: The 30th Newfoundland Electrical and Computer Engineering Conference (NECEC), St. John's, Canada.
    
- id: url:https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-159/MP-MSG-159-08.pdf
  date: 2018-11-1
  title: 'Holographic Displays: Emerging Technologies and Use Cases in Defence Applications'
  publisher: 'NATO MSG-159 2018 Annual M&S Conference.'

- id: doi:10.4043/27392-MS
  publisher: OTC Arctic Technology Conference, St. John's, Canada, October 2016.

- id: doi:10.1002/sdtp.12268

- id: doi:10.4043/25525-MS
  publisher: OTC Arctic Technology Conference, Copenhagen, Denmark, March 2015.