- id: doi:10.1097/HP.0000000000001732
  image: 
  date: '2023-09-1'
  title: 'Response to McCollough et al.'
  publisher: 'Health Physics 125(5):p 376'

- id: doi:10.1109/MCOM.004.2200627
  image: 
  date: '2023-10-2'
  title: 'Visual Twin for Pipeline Leak Detection'
  publisher: 'Abu Dhabi International Petroleum Exhibition and Conference (ADIPEC)'

- id: doi:10.1109/MCOM.004.2200627
  image: 
  date: '2023-09-1'
  title: 'Immersive Media and the Metaverse'
  publisher: 'IEEE Communications Magazine ( Volume: 61, Issue: 9, September 2023)'


- id: doi:10.1097/HP.0000000000001705
  image: 
  date: '2023-09-1'
  title: 'Radiation exposure from the patient perspective: an argument for the inclusion of dose history'
  publisher: 'Health Physics 125(3):p 198-201'

- id: url:https://ieeexplore.ieee.org/abstract/document/10019614
  image: https://www.vaclab.ca/images/foldpaper.PNG
  date: '2022-12-5'
  title: 'On Requirements for Field of Light Displays to Pass the Visual Turing Test'
  publisher: '2022 IEEE International Symposium on Multimedia (ISM)'


- id: url:https://www.cs.mun.ca/~mhamilton/papers/Hamilton.pdf
  image: https://www.vaclab.ca/images/foldpaper.PNG
  date: '2021-10-24'
  title: 'Visualization Using Field of Light Displays: Opportunities and New Questions'
  publisher: 'VisXVision: Workshop on Novel Directions in Vision Science and Visualization Research at IEEE Visualization 2021 Conference.'
  
- id: url:https://www.cs.mun.ca/~mhamilton/papers/nwells-hamilton-Necec2021.pdf
  image: https://www.vaclab.ca/images/wellspaper.png
  date: '2021-11-18'
  title: Towards Immersive Cinematic Video for Immersive Displays
  publisher: The 30th Newfoundland Electrical and Computer Engineering Conference (NECEC), St. John's, Canada.
  
   
- id: url:https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-159/MP-MSG-159-08.pdf
  date: 2018-11-1
  title: 'Holographic Displays: Emerging Technologies and Use Cases in Defence Applications'
  image: 
  publisher: 'NATO MSG-159 2018 Annual M&S Conference.'

- id: doi:10.4043/27392-MS
  publisher: OTC Arctic Technology Conference, St. John's, Canada, October 2016.
  image: https://www.vaclab.ca/images/flowvasepaper.PNG

- id: doi:10.4043/25525-MS
  publisher: OTC Arctic Technology Conference, Copenhagen, Denmark, March 2015.
  image: https://www.vaclab.ca/images/vasepaper.PNG
  
  
- id: doi:10.1002/sdtp.12268
  image: https://www.vaclab.ca/images/simpaper.PNG  
  
- id: doi:10.1529/biophysj.107.116053
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006349508703783-gr2.jpg
  
- id: doi:10.1007/11847250_21
  
- id: doi:10.4230/DagSemProc.07281.3
